#Configuraciones del juego

#Combate
PROBABILIDAD_HUIR = 0.5
PROBABILIDAD_ITEM = 0.6
VIDA_PIZZA_INICIAL = 100
REDUCCION_VIDA_PIZZA_POR_TURNO = 5

#Experiencia y Niveles
EXP_PARA_SUBIR_NIVEL = 100
BONUS_VIDA_NIVEL = 50
BONUS_FUERZA_NIVEL = 5
BONUS_DEFENSA_NIVEL = 2
BONUS_VELOCIDAD_NIVEL = 2

#Mapa
ANCHO_MAPA = 5
LARGO_MAPA = 20
PROB_CAMBIO_CAMINO = 0.2
ENEMIGOS_MIN_POR_MAPA = 5
ENEMIGOS_MAX_POR_MAPA = 7
PROB_ENEMIGO_OBJETIVO = 0.4

#Utilidades
VELOCIDAD_TEXTO = 0.03
